name: go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.8'
      - run: go build
      - uses: actions/upload-artifact@v1
        with:
          name: TODO
          path: TODO
